### ISSUE TITLE
Six Months Out of Date (Over 19 versions behind)

### ISSUE THREAD

**Issue by ChristianSilvermoon** [flathub/io.github.hydrusnetwork.hydrus#12]
Version is [v499](https://github.com/hydrusnetwork/hydrus/releases/tag/v499) is from September 7th, 2022

And the latest version is [v519](https://github.com/hydrusnetwork/hydrus/releases/tag/v519) as of the time of writing

**Comment by bbhtt** [comment]
Hello, please test https://github.com/flathub/io.github.hydrusnetwork.hydrus/pull/13 and let us know if it works.

**Comment by ChristianSilvermoon** [comment]
> Hello, please test #13 and let us know if it works.

The flatpakref file 404s for me, is there some way I can acquire what I'm intended to test?

**Comment by bbhtt** [comment]
> > Hello, please test #13 and let us know if it works.
> 
> The flatpakref file 404s for me, is there some way I can acquire what I'm intended to test?

I can start another build for you whenever you want. The test build stays alive for 4–5 days I think

**Comment by ChristianSilvermoon** [comment]
Taking a loose look at things it was able to Update my (rather sizable) database from v499 to v534 and appears to be operating normally ^^

After a few hours of normal use, I've encountered no unexpected behavior

**Comment by bbhtt** [comment]
Thanks! I'll merge in a day or two.

**Comment by ChristianSilvermoon** [comment]
Update: Anything using MPV does **not** work and instead shows a blank space with media controls
```
v534, 2023/07/09 09:43:10: [MPV error] vo/gpu: VT_GETMODE failed: Inappropriate ioctl for device

v534, 2023/07/09 09:43:10: [MPV error] vo/gpu: Failed to create GBM surface.

v534, 2023/07/09 09:43:10: [MPV error] vo/gpu: Failed to setup GBM.

v534, 2023/07/09 09:43:10: [MPV fatal] cplayer: Error opening/initializing the selected video_out (--vo) device.

v534, 2023/07/09 09:43:10: [MPV error] vo/gpu: Can't handle VT release - signal already used

v534, 2023/07/09 09:43:10: [MPV error] vo/gpu: Failed to create GBM surface.

v534, 2023/07/09 09:43:10: [MPV error] vo/gpu: Failed to setup GBM.

v534, 2023/07/09 09:43:10: [MPV fatal] cplayer: Error opening/initializing the VO window.

v534, 2023/07/09 09:43:10: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
```

**Comment by bbhtt** [comment]
Thanks I'll look into it. It's probably because MPV build is missing X11 support.

**Comment by bbhtt** [comment]
Ok. I pushed a fix https://github.com/flathub/io.github.hydrusnetwork.hydrus/pull/13/commits/0dfdaf820279347c90c505dd151d776bd0c57ed8. Please test once the build is done in ~20 minutes

Thanks!

**Comment by ChristianSilvermoon** [comment]
I can confirm that fixed the MPV issue~♪

**Comment by bbhtt** [comment]
I have merged the changes. The new version should be available in 4–5 hours. You can uninstall the test version (`flatpak remove io.github.hydrusnetwork.hydrus` will give you a choice if you have both the test and Flathub ones installed, choose the test version) and update.

Feel free to open issues if anything is wrong.

Thanks!
