### ISSUE TITLE
Hydrus not launching with a proper Gui after update

### ISSUE THREAD

**Issue by Iron-Squid** [flathub/io.github.hydrusnetwork.hydrus#167]
Distro: Fedora 39

I've recently updated both my system packages and my flatpak packages, and noticed that Hydrus isn't properly launching a gui.
![Screenshot from 2024-07-06 07-28-26](https://github.com/flathub/io.github.hydrusnetwork.hydrus/assets/68481224/75500c8b-fbda-4c38-9f57-01f090c5d11f)

I've reinstalled the flatpak in order to get it to work properly, but I haven't been able to resolve it.

**Comment by bbhtt** [comment]
Seems to work fine for me. When you launch from the terminal do you see anything?

Can you check if any other application from here https://flathub.org/apps/search?runtime=org.kde.Platform%2Fx86_64%2F6.7 has the same issue?

**Comment by Iron-Squid** [comment]
The output when running `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=hydrus_client io.github.hydrusnetwork.hydrus` is:
```
F: Not sharing "/usr/share/themes" with sandbox: Path "/usr" is reserved by Flatpak
F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak
The given db path "/app/hydrus/db" is not writeable-to! Falling back to userpath at "/home/squid/Hydrus".
v581, 2024-07-10 22:50:58: hydrus client started
v581, 2024-07-10 22:51:00: booting controller…
v581, 2024-07-10 22:51:00: booting db…
v581, 2024-07-10 22:51:01: checking database
v581, 2024-07-10 22:51:02: initialising managers
v581, 2024-07-10 22:51:02: booting gui…
```


I have tested a few other apps listed in the page you described. 
Another app sharing the problem is [Prism Launcher](https://flathub.org/apps/org.prismlauncher.PrismLauncher)
- Prism Launcher had actually successfully launched the GUI exactly once, but then was unable to do so when quitting after having created an instance of Minecraft within the program. I see that I'm able to continue booting the GUI successfully so long as I don't create a Minecraft instance within the program. I've confirmed this by purging the `~/.var/app` folder and experimenting with what causes the GUI to not display.

Other apps in recent times that also shared the problem were Calibre from flathub. After reinstalling it however it was able to launch the GUI properly. It's not listed on the webpage you linked, so I don't know if it's related to this issue.


Interestingly, some other apps I've installed from that same webpage you linked display their GUIs just fine. like Kdenlive and Dolphin Emulator. They both don't seem to display this issue, but I haven't tested various functions of their GUIs in depth to see if they also display this behavior.

This may be worth a more general bug report, seeing as it seems to affect more than one app, but I'm not sure of how to confirm that it's not just a case of something being misconfigured on my system.

**Comment by Iron-Squid** [comment]
For what it's worth, I've run `flatpak repair`, no change

**Comment by Iron-Squid** [comment]
Nevermind about Kdenlive. I just updated all of my flatpaks out of curiousity that it might fix the problem. Kdenlive now displays the same issue, though Dolphin Emulator still works, in addition to Kid3.

**Comment by bbhtt** [comment]
What is the Mesa version on your host? This can happen if the Mesa in the runtime and host versions differ by a major version.

**Comment by Iron-Squid** [comment]
When I have time tomorrow, I'll test this out on my laptop. Hydrus had also been unable to launch a GUI there after updating as well.

**Comment by Iron-Squid** [comment]
> What is the Mesa version on your host? This can happen if the Mesa in the runtime and host versions differ by a major version.

The relevant portion of the output of `glxinfo -B` is
```
OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.3.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
```

I'm not sure of how to check the Mesa version associated with these runtimes, nor of how to resolve it. Perhaps by temporarily downgrading my Mesa package?

**Comment by bbhtt** [comment]
Mesa 24.1 is in runtime, downgrading won't help. You need to check if updating your host Mesa works.

**Comment by Iron-Squid** [comment]
> Mesa 24.1 is in runtime, downgrading won't help. You need to check if updating your host Mesa works.

https://discussion.fedoraproject.org/t/will-mesa-24-make-its-way-down-to-fedora-39/106788/2

Darn, I'll have to wait until Fedora 40 releases in order to have these working again.

**Comment by Iron-Squid** [comment]
Update: I live in a cave. Fedora 40 has been out since April 2024.

I'll upgrade my distro when I get home from work.

**Comment by Iron-Squid** [comment]
Update: Everything is working.

For context, I disabled the GNOME Software app's automatic update system, so I wasn't notified of the fact that a new version of Fedora had released. I don't follow developments nor update cycles of any project too closely, so I was also unaware through those methods as well.

Closing.

**Comment by Iron-Squid** [comment]
Wrong closing.

**Comment by Iron-Squid** [comment]
Wrong closing, pardon.

**Comment by Iron-Squid** [comment]
Pardon
