### ISSUE TITLE
Minimizing to system tray makes the tray icon disappear

### ISSUE THREAD

**Issue by head-yote** [flathub/io.github.hydrusnetwork.hydrus#4]
Hi, not sure if this is where issues for the flatpak are to be posted.

Upon startup, Hydrus launches normally, with its application window hidden and tray icon visible. After unminimizing, then reminimizing the application, its tray icon disappears and there's no way to get the application window back. There is no console output/errors when this happens.

I have the following options checked under options -> system tray:
Always show the hydrus system tray icon
Mimimise the main window to system tray
Close the main window to system tray
Start the client minimised to system tray

Using:
KDE
Hydrus v499
Arch Linux

This functionality has been working normally for me for years on the AUR version of hydrus. It is difficult to test the rest of the program in any real long-term capacity with this bug active.

**Comment by bbhtt** [comment]
> Hello can you please test #13 and let us know if it works now?

Seems to be fixed for  me

**Comment by bbhtt** [comment]
Hello, please update and let me know if this is fixed. If not I can reopen. Thanks!
