### ISSUE TITLE
Issues with AV1-encoded MKVs

### ISSUE THREAD

**Issue by head-yote** [flathub/io.github.hydrusnetwork.hydrus#5]
Hi, not sure if this is where issues for the flatpak are to be posted.

Pre-existing AV1 codec MKVs in a Hydrus library play audio, but have black/blank video output. Trying to import a new AV1-encoded MKV results in an error:
"Video appears to be broken and non-renderable--perhaps a damaged single-frame video?"

I'm not clear on if this is in scope of the flatpak or not, but a normal AUR-based Hydrus install will import and play these files properly, so I'm guessing one of the libraries (ffmpeg/mpv?) that is being used is not up to date or not the right version.

I've attached a short test file that can be used.
[cat.zip](https://github.com/flathub/io.github.hydrusnetwork.hydrus/files/9639819/cat.zip)

Packages I think were used for my AUR hydrus build:
FFmpeg 5.1.1
Python-mpv 1.0.1
MPV 1:0.34.1

I noticed the python requirements for Hydrus list python-mpv 0.4.5 specifically, which is 3 years old at this point. The AUR version just grabs the most recent version and doesn't seem to care. Not sure if this is the culprit, and if so if this should be updated to a newer version in the main hydrus repo or if there's a reason it's not.

**Comment by bbhtt** [comment]
This is probably because ffmpeg in the manifest is built without any AV1 decoders. I'll probably switch it to base ffmpeg from SDK or ffmpeg-full from SDK instead of building here.

**Comment by bbhtt** [comment]
Hello, please test the build here https://github.com/flathub/io.github.hydrusnetwork.hydrus/pull/14 and let me know if the issues is fixed. I added the aom and dav1d decoders.

I tested with a [sample AV1](https://github.com/SPBTV/video_av1_samples), and it works fine for me. Thanks!

**Comment by bbhtt** [comment]
OK I can play the video you attached with the test build above. I'll merge it.
