### ISSUE TITLE
New release v504 is out now.

### ISSUE THREAD

**Issue by Kirtai** [flathub/io.github.hydrusnetwork.hydrus#9]
New release v504 is out now.

**Comment by Viktini** [comment]
For what it's worth, Hydrus pushes an update typically [every Wednesday](https://github.com/hydrusnetwork/hydrus). Would it be feasible to do the same here, or at least fortnightly? It's at v517 right now.

**Comment by bbhtt** [comment]
Hello, please test https://github.com/flathub/io.github.hydrusnetwork.hydrus/pull/13 and let us know if it works.
